### ISSUE TITLE
Implementing React To Project

### ISSUE THREAD

**Issue by TBicer** [BilgeAdam-Akademi-Students/bilgeadam-students-main#1]
Merhaba, Arkadaşlar projemizi öncelikle react.js altyapısına geçirerek işlevselliğimizi daha üst seviyeye çıkarabiliriz. Bu konuda yorumlarınızı bekliyorum.

**Comment by Caslantas** [comment]
Olabilir ama reactta bootstrap kullanmayı ben bilmiyorum ama   bulma diye bişey var reacta css uygulamak için kullanılabilir

**Comment by Caslantas** [comment]
react ile ne yapabilirizki onu düşünüyorum şimdi güzel fikri olan varmı   tasarımını  bootstrap ile çok güzel yapabilirz kartlar açılabilir kart şeklinde olabilir  her tıklandığında kart açıldığında  oraya herkes  kendi ile alakalı birşeyler ekleyebilir.benim aklıma bu geldi

**Comment by TBicer** [comment]
HTML ve CSS ile yapabileceğimiz her şeyi React.Js ile de yapabiliriz. Ekstra olarak React ile çalışmak component yapısını getireceği için herkes kendi alanı üzerinde çalışacağı için projeyi bir araya getirmesi ve hataları çözmesi daha kolay olacaktır. Ekstra olarak bulma gibi hazır template kullanmaya karşıyım sonuç olarak bu bizim yazmamız gereken bir site. Bootstrap gibi hazır kütüphanelerden ızgara sistemini kullanabiliriz. Böylece flex veya grid kullanırken bu yapıyı responsive yapmak için ekstra çaba harcamamıza gerek kalmaz.

**Comment by muratakdag** [comment]
Katkılarınız için teşekkürler. Yeni issue'larda görüşmek üzere
